### ISSUE TITLE
README can have more enhancements

### ISSUE THREAD

**Issue by Git-Harshit** [Nish251103/Virtual-Assistant#1]
Hey @Nish251103, Your [README](./README.md) file contains some typos, and can have certain enhancements like better formatting at describing code usage. 

Here's how it currently looks:
![Capture-README-VA](https://user-images.githubusercontent.com/57865187/94909962-95998e80-04c1-11eb-8175-ca32418be0df.PNG)

Please let me work on this issue. I can improve the README, and can add further descriptions wherever needed.

**Comment by Nish251103** [comment]
sure, go for it.
